#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("EggChat.Resource", IsApplication=true)]

namespace EggChat
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int b1 = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int b10 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int b11 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int b12 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int b13 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int b14 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int b2 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int b3 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int b4 = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int b5 = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int b6 = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int b7 = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int b8 = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int b9 = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int custom_background = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int f1 = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int f2 = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int f3 = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int f4 = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int f5 = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int f6 = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int f7 = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int f8 = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int f9 = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int Icon = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int pika = 2130837529;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050000
			public const int btnChat = 2131034112;
			
			// aapt resource value: 0x7f05000d
			public const int btnLogin = 2131034125;
			
			// aapt resource value: 0x7f050001
			public const int btnMap = 2131034113;
			
			// aapt resource value: 0x7f050013
			public const int btnSendMsg = 2131034131;
			
			// aapt resource value: 0x7f050005
			public const int btn_open = 2131034117;
			
			// aapt resource value: 0x7f05000a
			public const int editEmail = 2131034122;
			
			// aapt resource value: 0x7f05000e
			public const int editFind = 2131034126;
			
			// aapt resource value: 0x7f050012
			public const int editMsg = 2131034130;
			
			// aapt resource value: 0x7f050008
			public const int editUserName = 2131034120;
			
			// aapt resource value: 0x7f050002
			public const int frameLayout = 2131034114;
			
			// aapt resource value: 0x7f05000c
			public const int gridview = 2131034124;
			
			// aapt resource value: 0x7f050003
			public const int head_image = 2131034115;
			
			// aapt resource value: 0x7f050016
			public const int img_icon = 2131034134;
			
			// aapt resource value: 0x7f050011
			public const int listMsg = 2131034129;
			
			// aapt resource value: 0x7f050010
			public const int listview = 2131034128;
			
			// aapt resource value: 0x7f050006
			public const int loginLayout = 2131034118;
			
			// aapt resource value: 0x7f050015
			public const int progressbar_updown = 2131034133;
			
			// aapt resource value: 0x7f05000f
			public const int refresher1 = 2131034127;
			
			// aapt resource value: 0x7f050004
			public const int txtDescrip = 2131034116;
			
			// aapt resource value: 0x7f050009
			public const int txtEmail = 2131034121;
			
			// aapt resource value: 0x7f05000b
			public const int txtHead = 2131034123;
			
			// aapt resource value: 0x7f050014
			public const int txtMsg = 2131034132;
			
			// aapt resource value: 0x7f050007
			public const int txtUserName = 2131034119;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Chat = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ItemRow = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Login = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Map = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Message = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int MsgItemRow = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int WelCome = 2130903047;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
