#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("EggChat.Resource", IsApplication=true)]

namespace EggChat
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int pull_in_left = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int push_out_right = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int rotate_centre = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int rotate_corner = 2130968579;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010003
			public const int buttonSize = 2130771971;
			
			// aapt resource value: 0x7f010002
			public const int circleCrop = 2130771970;
			
			// aapt resource value: 0x7f010004
			public const int colorScheme = 2130771972;
			
			// aapt resource value: 0x7f010001
			public const int imageAspectRatio = 2130771969;
			
			// aapt resource value: 0x7f010000
			public const int imageAspectRatioAdjust = 2130771968;
			
			// aapt resource value: 0x7f010005
			public const int scopeUris = 2130771973;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f080018
			public const int barDarkColor = 2131230744;
			
			// aapt resource value: 0x7f08001a
			public const int barLightColor = 2131230746;
			
			// aapt resource value: 0x7f080019
			public const int barMeduimColor = 2131230745;
			
			// aapt resource value: 0x7f080008
			public const int common_action_bar_splitter = 2131230728;
			
			// aapt resource value: 0x7f08001b
			public const int common_google_signin_btn_text_dark = 2131230747;
			
			// aapt resource value: 0x7f080009
			public const int common_google_signin_btn_text_dark_default = 2131230729;
			
			// aapt resource value: 0x7f08000b
			public const int common_google_signin_btn_text_dark_disabled = 2131230731;
			
			// aapt resource value: 0x7f08000c
			public const int common_google_signin_btn_text_dark_focused = 2131230732;
			
			// aapt resource value: 0x7f08000a
			public const int common_google_signin_btn_text_dark_pressed = 2131230730;
			
			// aapt resource value: 0x7f08001c
			public const int common_google_signin_btn_text_light = 2131230748;
			
			// aapt resource value: 0x7f08000d
			public const int common_google_signin_btn_text_light_default = 2131230733;
			
			// aapt resource value: 0x7f08000f
			public const int common_google_signin_btn_text_light_disabled = 2131230735;
			
			// aapt resource value: 0x7f080010
			public const int common_google_signin_btn_text_light_focused = 2131230736;
			
			// aapt resource value: 0x7f08000e
			public const int common_google_signin_btn_text_light_pressed = 2131230734;
			
			// aapt resource value: 0x7f08001d
			public const int common_plus_signin_btn_text_dark = 2131230749;
			
			// aapt resource value: 0x7f080000
			public const int common_plus_signin_btn_text_dark_default = 2131230720;
			
			// aapt resource value: 0x7f080002
			public const int common_plus_signin_btn_text_dark_disabled = 2131230722;
			
			// aapt resource value: 0x7f080003
			public const int common_plus_signin_btn_text_dark_focused = 2131230723;
			
			// aapt resource value: 0x7f080001
			public const int common_plus_signin_btn_text_dark_pressed = 2131230721;
			
			// aapt resource value: 0x7f08001e
			public const int common_plus_signin_btn_text_light = 2131230750;
			
			// aapt resource value: 0x7f080004
			public const int common_plus_signin_btn_text_light_default = 2131230724;
			
			// aapt resource value: 0x7f080006
			public const int common_plus_signin_btn_text_light_disabled = 2131230726;
			
			// aapt resource value: 0x7f080007
			public const int common_plus_signin_btn_text_light_focused = 2131230727;
			
			// aapt resource value: 0x7f080005
			public const int common_plus_signin_btn_text_light_pressed = 2131230725;
			
			// aapt resource value: 0x7f080014
			public const int listViewBg = 2131230740;
			
			// aapt resource value: 0x7f080017
			public const int sendDarkColor = 2131230743;
			
			// aapt resource value: 0x7f080015
			public const int sendLightColor = 2131230741;
			
			// aapt resource value: 0x7f080016
			public const int sendMeduimColor = 2131230742;
			
			// aapt resource value: 0x7f080011
			public const int textColor = 2131230737;
			
			// aapt resource value: 0x7f080012
			public const int textFieldColor = 2131230738;
			
			// aapt resource value: 0x7f080013
			public const int textShadow = 2131230739;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int b1 = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int b10 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int b11 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int b12 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int b13 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int b14 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int b2 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int b3 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int b4 = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int b5 = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int b6 = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int b7 = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int b8 = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int b9 = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int bubble = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int common_full_open_on_phone = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int common_google_signin_btn_icon_dark = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int common_google_signin_btn_icon_dark_disabled = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int common_google_signin_btn_icon_dark_focused = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int common_google_signin_btn_icon_dark_normal = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int common_google_signin_btn_icon_dark_pressed = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int common_google_signin_btn_icon_light = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int common_google_signin_btn_icon_light_disabled = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int common_google_signin_btn_icon_light_focused = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int common_google_signin_btn_icon_light_normal = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int common_google_signin_btn_icon_light_pressed = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int common_google_signin_btn_text_dark = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int common_google_signin_btn_text_dark_disabled = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int common_google_signin_btn_text_dark_focused = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int common_google_signin_btn_text_dark_normal = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int common_google_signin_btn_text_dark_pressed = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int common_google_signin_btn_text_light = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int common_google_signin_btn_text_light_disabled = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int common_google_signin_btn_text_light_focused = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int common_google_signin_btn_text_light_normal = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int common_google_signin_btn_text_light_pressed = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int common_ic_googleplayservices = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int common_plus_signin_btn_icon_dark = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int common_plus_signin_btn_icon_dark_disabled = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int common_plus_signin_btn_icon_dark_focused = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int common_plus_signin_btn_icon_dark_normal = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int common_plus_signin_btn_icon_dark_pressed = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int common_plus_signin_btn_icon_light = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int common_plus_signin_btn_icon_light_disabled = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int common_plus_signin_btn_icon_light_focused = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int common_plus_signin_btn_icon_light_normal = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int common_plus_signin_btn_icon_light_pressed = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int common_plus_signin_btn_text_dark = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int common_plus_signin_btn_text_dark_disabled = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int common_plus_signin_btn_text_dark_focused = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int common_plus_signin_btn_text_dark_normal = 2130837554;
			
			// aapt resource value: 0x7f020033
			public const int common_plus_signin_btn_text_dark_pressed = 2130837555;
			
			// aapt resource value: 0x7f020034
			public const int common_plus_signin_btn_text_light = 2130837556;
			
			// aapt resource value: 0x7f020035
			public const int common_plus_signin_btn_text_light_disabled = 2130837557;
			
			// aapt resource value: 0x7f020036
			public const int common_plus_signin_btn_text_light_focused = 2130837558;
			
			// aapt resource value: 0x7f020037
			public const int common_plus_signin_btn_text_light_normal = 2130837559;
			
			// aapt resource value: 0x7f020038
			public const int common_plus_signin_btn_text_light_pressed = 2130837560;
			
			// aapt resource value: 0x7f020039
			public const int custom_background = 2130837561;
			
			// aapt resource value: 0x7f02003a
			public const int f1 = 2130837562;
			
			// aapt resource value: 0x7f02003b
			public const int f2 = 2130837563;
			
			// aapt resource value: 0x7f02003c
			public const int f3 = 2130837564;
			
			// aapt resource value: 0x7f02003d
			public const int f4 = 2130837565;
			
			// aapt resource value: 0x7f02003e
			public const int f5 = 2130837566;
			
			// aapt resource value: 0x7f02003f
			public const int f6 = 2130837567;
			
			// aapt resource value: 0x7f020040
			public const int f7 = 2130837568;
			
			// aapt resource value: 0x7f020041
			public const int f8 = 2130837569;
			
			// aapt resource value: 0x7f020042
			public const int f9 = 2130837570;
			
			// aapt resource value: 0x7f020043
			public const int Icon = 2130837571;
			
			// aapt resource value: 0x7f020044
			public const int leftmsg = 2130837572;
			
			// aapt resource value: 0x7f020045
			public const int Map = 2130837573;
			
			// aapt resource value: 0x7f020046
			public const int pika = 2130837574;
			
			// aapt resource value: 0x7f020047
			public const int rightmsg = 2130837575;
			
			// aapt resource value: 0x7f020048
			public const int where = 2130837576;
			
			// aapt resource value: 0x7f020049
			public const int where2 = 2130837577;
			
			// aapt resource value: 0x7f02004a
			public const int where3 = 2130837578;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f090000
			public const int adjust_height = 2131296256;
			
			// aapt resource value: 0x7f090001
			public const int adjust_width = 2131296257;
			
			// aapt resource value: 0x7f090006
			public const int auto = 2131296262;
			
			// aapt resource value: 0x7f090009
			public const int btnChat = 2131296265;
			
			// aapt resource value: 0x7f090016
			public const int btnLogin = 2131296278;
			
			// aapt resource value: 0x7f09000a
			public const int btnMap = 2131296266;
			
			// aapt resource value: 0x7f09001e
			public const int btnSendMsg = 2131296286;
			
			// aapt resource value: 0x7f09000e
			public const int btn_open = 2131296270;
			
			// aapt resource value: 0x7f09001b
			public const int chkMap = 2131296283;
			
			// aapt resource value: 0x7f090007
			public const int dark = 2131296263;
			
			// aapt resource value: 0x7f090013
			public const int editEmail = 2131296275;
			
			// aapt resource value: 0x7f090017
			public const int editFind = 2131296279;
			
			// aapt resource value: 0x7f09001d
			public const int editMsg = 2131296285;
			
			// aapt resource value: 0x7f090011
			public const int editUserName = 2131296273;
			
			// aapt resource value: 0x7f09000b
			public const int frameLayout = 2131296267;
			
			// aapt resource value: 0x7f090015
			public const int gridview = 2131296277;
			
			// aapt resource value: 0x7f09000c
			public const int head_image = 2131296268;
			
			// aapt resource value: 0x7f090003
			public const int icon_only = 2131296259;
			
			// aapt resource value: 0x7f090023
			public const int img_icon = 2131296291;
			
			// aapt resource value: 0x7f09001f
			public const int imvFriend = 2131296287;
			
			// aapt resource value: 0x7f090021
			public const int imvMy = 2131296289;
			
			// aapt resource value: 0x7f090008
			public const int light = 2131296264;
			
			// aapt resource value: 0x7f09001c
			public const int listMsg = 2131296284;
			
			// aapt resource value: 0x7f090019
			public const int listview = 2131296281;
			
			// aapt resource value: 0x7f09000f
			public const int loginLayout = 2131296271;
			
			// aapt resource value: 0x7f090002
			public const int none = 2131296258;
			
			// aapt resource value: 0x7f090022
			public const int progressbar_updown = 2131296290;
			
			// aapt resource value: 0x7f090018
			public const int refresher1 = 2131296280;
			
			// aapt resource value: 0x7f090004
			public const int standard = 2131296260;
			
			// aapt resource value: 0x7f09000d
			public const int txtDescrip = 2131296269;
			
			// aapt resource value: 0x7f090012
			public const int txtEmail = 2131296274;
			
			// aapt resource value: 0x7f090014
			public const int txtHead = 2131296276;
			
			// aapt resource value: 0x7f090020
			public const int txtMsg = 2131296288;
			
			// aapt resource value: 0x7f090010
			public const int txtUserName = 2131296272;
			
			// aapt resource value: 0x7f090005
			public const int wide = 2131296261;
			
			// aapt resource value: 0x7f09001a
			public const int wvMap = 2131296282;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f070000
			public const int google_play_services_version = 2131165184;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Chat = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ItemRow = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Login = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Map = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Message = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int MsgItemRow = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int WelCome = 2130903047;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f050000
			public const int sound2 = 2131034112;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060020
			public const int ApplicationName = 2131099680;
			
			// aapt resource value: 0x7f06001f
			public const int Hello = 2131099679;
			
			// aapt resource value: 0x7f060001
			public const int auth_google_play_services_client_facebook_display_name = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int auth_google_play_services_client_google_display_name = 2131099648;
			
			// aapt resource value: 0x7f060018
			public const int common_google_play_services_api_unavailable_text = 2131099672;
			
			// aapt resource value: 0x7f06000a
			public const int common_google_play_services_enable_button = 2131099658;
			
			// aapt resource value: 0x7f060009
			public const int common_google_play_services_enable_text = 2131099657;
			
			// aapt resource value: 0x7f060008
			public const int common_google_play_services_enable_title = 2131099656;
			
			// aapt resource value: 0x7f060007
			public const int common_google_play_services_install_button = 2131099655;
			
			// aapt resource value: 0x7f060005
			public const int common_google_play_services_install_text_phone = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int common_google_play_services_install_text_tablet = 2131099654;
			
			// aapt resource value: 0x7f060004
			public const int common_google_play_services_install_title = 2131099652;
			
			// aapt resource value: 0x7f060013
			public const int common_google_play_services_invalid_account_text = 2131099667;
			
			// aapt resource value: 0x7f060012
			public const int common_google_play_services_invalid_account_title = 2131099666;
			
			// aapt resource value: 0x7f060011
			public const int common_google_play_services_network_error_text = 2131099665;
			
			// aapt resource value: 0x7f060010
			public const int common_google_play_services_network_error_title = 2131099664;
			
			// aapt resource value: 0x7f060003
			public const int common_google_play_services_notification_ticker = 2131099651;
			
			// aapt resource value: 0x7f06001c
			public const int common_google_play_services_restricted_profile_text = 2131099676;
			
			// aapt resource value: 0x7f06001b
			public const int common_google_play_services_restricted_profile_title = 2131099675;
			
			// aapt resource value: 0x7f06001a
			public const int common_google_play_services_sign_in_failed_text = 2131099674;
			
			// aapt resource value: 0x7f060019
			public const int common_google_play_services_sign_in_failed_title = 2131099673;
			
			// aapt resource value: 0x7f060002
			public const int common_google_play_services_unknown_issue = 2131099650;
			
			// aapt resource value: 0x7f060015
			public const int common_google_play_services_unsupported_text = 2131099669;
			
			// aapt resource value: 0x7f060014
			public const int common_google_play_services_unsupported_title = 2131099668;
			
			// aapt resource value: 0x7f060016
			public const int common_google_play_services_update_button = 2131099670;
			
			// aapt resource value: 0x7f06000c
			public const int common_google_play_services_update_text = 2131099660;
			
			// aapt resource value: 0x7f06000b
			public const int common_google_play_services_update_title = 2131099659;
			
			// aapt resource value: 0x7f06000f
			public const int common_google_play_services_updating_text = 2131099663;
			
			// aapt resource value: 0x7f06000e
			public const int common_google_play_services_updating_title = 2131099662;
			
			// aapt resource value: 0x7f06000d
			public const int common_google_play_services_wear_update_text = 2131099661;
			
			// aapt resource value: 0x7f060017
			public const int common_open_on_phone = 2131099671;
			
			// aapt resource value: 0x7f06001d
			public const int common_signin_button_text = 2131099677;
			
			// aapt resource value: 0x7f06001e
			public const int common_signin_button_text_long = 2131099678;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] LoadingImageView = new int[] {
					2130771968,
					2130771969,
					2130771970};
			
			// aapt resource value: 2
			public const int LoadingImageView_circleCrop = 2;
			
			// aapt resource value: 1
			public const int LoadingImageView_imageAspectRatio = 1;
			
			// aapt resource value: 0
			public const int LoadingImageView_imageAspectRatioAdjust = 0;
			
			public static int[] SignInButton = new int[] {
					2130771971,
					2130771972,
					2130771973};
			
			// aapt resource value: 0
			public const int SignInButton_buttonSize = 0;
			
			// aapt resource value: 1
			public const int SignInButton_colorScheme = 1;
			
			// aapt resource value: 2
			public const int SignInButton_scopeUris = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
